apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  storageClassName: shared-storage  # Reference the StorageClass
  accessModes:
    - ReadWriteMany  # Allow multiple pods to use the same PVC
  resources:
    requests:
      storage: 5Gi  # Must be equal or less than the PV size
